server:
  host: 127.0.0.1
  port: 5000

#database
database:
  host: 127.0.0.1
  user: postgres
  password: "00213254"
  dbName: example
  port: 5432
  sslMode: disable
  timezone: Asia/Tehran

# migration
dsn: "postgres://172.17.0.5/example?sslmode=disable&user=postgres&password=00213254"
